[package]
name = "tests_crate"
version = "0.1.0"
edition = "2021"


[workspace]

[dev-dependencies]
native_model = { path = "../" }
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
anyhow = "1.0.44"